### ISSUE TITLE
Problem with movies download

### ISSUE THREAD

**Issue by lozziboy** [ccrisan/motioneyeos#106]
First of all thank you for this wonderful software, you are doing a great job!
I encountered a problem with the download function on the movies section (attached picture): when you try to download big movies (>500MB) the download doesn't work. Infact sometimes it waits but doesn't start and some other times it starts but the downloaded file is completely empty (0 bytes).

![download](https://cloud.githubusercontent.com/assets/16566804/12130803/d9da9210-b40d-11e5-9236-d9cf31b73c3a.png)

**Comment by ccrisan** [comment]
Files of that size will never be downloadable via motionEye's UI and server, on a regular ARM-based board. The reason is that motionEye server (based on Tornado) hasn't been optimized to serve so-called *static files* and eats up a lot of CPU when dealing with this kind of files. Generally I don't recommend configuring your motionEye to generate movies this big.

If you really need to generate large movies, try saving them on a remote server and serving them via Nginx or other means.
