### ISSUE TITLE
how i can reset password root or admin in SSH?

### ISSUE THREAD

**Issue by fuentes277** [ccrisan/motioneyeos#1311]
hello
i login in ssh with password empty and when executed 
#passwd root
message: password for root changed by root
try login and message:
WARNING: your password has expired
You must change your password now and login again
Changing password for root
i change password for root
message:
passwd : /etc/passwd: Read-only file system
passwd: cant update password file /etc/passwd
Connection to ***** closed.
also use command:
#mount -o remount,rw /
#mount -o remount,rw /boot
for change password root and when i try login, show WARNING...

**Comment by ccrisan** [comment]
Don't worry about the read-only part. It actually updates the `/data/etc/shadow` file where the hash is kept.

Normally you should change the root password via the UI (the admin password). Otherwise, you could use the `adminpasswd` script to do that. Using `passwd` should also work, but you get unwanted warnings. I'm not sure about the expiration part; `adminpasswd` will remove expiration from your password anyways.
