### ISSUE TITLE
wget command not found

### ISSUE THREAD

**Issue by CheetahGod** [ccrisan/motioneyeos#1504]
While trying to connect motion eye os running on my raspberry pi to google drive the wget command is not found.

**Comment by ccrisan** [comment]
@CheetahGod, this issue is invalid for the following reasons:

 * you have totally ignored the issue template we have in place
 * you have not read our [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ#can-i-install-some-package) which clearly says that this is not a regular OS where you can install stuff

Long story short: use `curl`.

**Comment by geronimo1400** [comment]
@ccrisan The confusion here is because your directions for connecting to Google Drive in your FAQ says to use wget.

**Comment by miaosun** [comment]
yes true @ccrisan , in the FAQ says to use wget, you should update it

**Comment by jasaw** [comment]
@geronimo1400 & @miaosun The Google Drive FAQ is obsolete, says so in bold on top of the page.

**Comment by duncangroenewald** [comment]
Better to replace the instructions with instructions for how to sync with Google drive then.  I can't seem to find any instruction for how to set that up.
