### ISSUE TITLE
Detect on dark field

### ISSUE THREAD

**Issue by alexei-developer** [ccrisan/motioneyeos#1538]
Hello, why detect angle on dark field?

RPi3
meye-7ffdc66b
motionEye Version | 0.39
Motion Version | 4.1.1
OS Version | motionEyeOS 20180401
![error_meyeos_detection](https://user-images.githubusercontent.com/4242358/41151029-36b60a3c-6b18-11e8-9d58-dcb46c67c8c5.png)

**Comment by jasaw** [comment]
Do you mean to ask why the red motion detection box goes into the blacked out area?
That's because the motion box is the smallest bounding rectangle that covers all the areas that have "motion" and it can only draw one rectangle. "motion" is just pixel intensity change (after despeckle filter if enable).
In your case, you have a T shaped detection zone, so if there's any "motion" at two of the edges of the T zone, you're going to get a red rectangle going into the blacked out area.

Hope that answers your question.

**Comment by alexei-developer** [comment]
Hello, top angle cannot be on dark field =) After experiments this sitatution exist only first 10 seconds after click button "Apply". Continue work without this problem =)
