### ISSUE TITLE
Raspberry PI Zero

### ISSUE THREAD

**Issue by rockman55** [ccrisan/motioneyeos#182]
Having an issued trying to write initial image to Raspberry Pi Zero. I have used both versions of the software   (20151103 and 20160109 motion eye). All I get is the rainbow screen at the beginning and nothing else happens. I have been using this software for some time on my Raspberry Pi 2 Model B with no problem. I would like to be able to use this Pi Zero with a USB webcam. Have seen some other request and posts about the Pi Zero but not sure if anyone has got it to work. Thanks

**Comment by ccrisan** [comment]
I haven't gotten my hands on a RPI0 yet. Sorry.

**Comment by hxpaul** [comment]
I have just installed this on a raspberry pi zero, install went smoothly using motioneyeos-raspberrypi-20160410.img and motioneye is running, but it does not recognise the camera. This is all new hardware today, there might be some other issue, I'll do some experimenting.

**Comment by hxpaul** [comment]
Pi Zero needed a firmware upgrade so I guess that needs a new build of motioneyeos

**Comment by ctrunk514** [comment]
Just an FYI in case anyone finds this post and has a similar issue.  I had Motioneye working perfectly on a PI3 with wifi and it was awesome. I took the micosd card out and threw it in a RPI0 and motioneye could not detect the camera.  Unable to open video device was all I could get.  I ran sudo apt-get dist-upgrade and bingo, the camera was detected and motion eye started working.  Hope this helps someone.

**Comment by kalgraff** [comment]
I try to run sudo apt-get dist-upgrade on MotionEyeOS, but it dos not work. Are you using MotionEyeOS or MotionEye?

**Comment by rockman55** [comment]
You cannot use apt-get dist-upgrade with MotionEyeOS. The only way to update is through the user interface.

Danny

**Comment by doughadfield** [comment]
I've just received my pi zero with camera cable, and I can confirm that motioneyeos doesn't work with the (original) pi camera on the zero board. Using a Raspbian lite image and mjpg-streamer (after updating firmware with rpi-update) the camera works fine, so it's definately the motioneyeos image that's the issue (using the latest). I would be happy to help with any beta testing.
Thanks again for this superb software!
Doug

**Comment by doughadfield** [comment]
btw, I tried copying the firmware file from the /boot filesystem of the raspbian image to the motioneyeos image, but that doesn't work (or I'm doing it wrong).

**Comment by ccrisan** [comment]
I'm working on it.

**Comment by raspberrycoulis** [comment]
How does installation work on a PiZero if it needs a network connection, but not LAN port? Can you use the wpa_supplicant trick (explained here: https://www.raspberrypi.org/blog/another-update-raspbian/) to preconfigure your WiFi network prior to first boot? Or is there another way to configure the WiFi without a physical LAN connection?

**Comment by ccrisan** [comment]
I have just updated the [troubleshooting page for RPI model A family](https://github.com/ccrisan/motioneyeos/wiki/Troubleshooting-Raspberry-PI-Models-A-(Plus)-And-Zero) to include instructions on how to preconfigure wifi with /boot/wpa_supplicant.conf.

**Comment by reggiekush** [comment]
@ctrunk514 Do you have a problem with it crashing on you? I've got my camera running at the lowest resolution and motioneye will crash as soon as I pull it up on a browser.

**Comment by ccrisan** [comment]
A new OS image with Zero and camera v2.1 support will be available later today.

**Comment by RudyRipDraw** [comment]
Hi,
For the RaspberryPI zero, I downloaded the image onto and SD and booted.
My PiZero has HDMI display, so I can watch what is going on, usb hub to keyboard/mouse and wifi dongle.  I know the wifi needs to be configured after booting, but according to the HDMI display, the PI zero is looking for a "network wired" interface, the reboots and retries.

Any help on what I'm doing wrong would be greatly appreciated.  BTW I got motioneye to work on the PI both on wifi and ethernet.

thanks

**Comment by ccrisan** [comment]
Can you please attach your log files here? Normally the OS requires a network connection, whether it's wired or wireless.

**Comment by fersd** [comment]
I'm going to try it on a pi zero. The highlighted link is for a pi zero correct?
![screenshot from 2016-08-11 02-29-34](https://cloud.githubusercontent.com/assets/20967311/17584481/9aed64a6-5f6b-11e6-8502-ee65c77b3d14.png)

**Comment by ccrisan** [comment]
Yes, that's the one.

**Comment by RudyRipDraw** [comment]
Let me start by just thanking you for all the work you have done on this and also your efforts to support this for people like me.

Just so that there is no confusion on the thread.

[cid:image004.png@01D1F3A9.A5BD1530]


This is photo of the HDMI boot screen, after the last line, it retries.  I hope this was the info you were asking for.  If not, let me know.

[cid:image002.png@01D1F3AA.098424A0]

**Comment by RudyRipDraw** [comment]
![screenhunter_2771 aug 11 08 23](https://cloud.githubusercontent.com/assets/13458260/17594291/ab5bbb26-5f9d-11e6-9bdc-0480c0ec091c.jpg)

**Comment by RudyRipDraw** [comment]
Sorry, new to communicating vi Git,    

After not finding the non-existent wired network, it reboots. 

I do have a powered USB-HUB--> wifi doggle, keyboard/mouse

thanks 

![screenhunter_2772 aug 11 08 30](https://cloud.githubusercontent.com/assets/13458260/17594387/fe31000e-5f9d-11e6-93b1-405d6d49e284.gif)

![screenhunter_2771 aug 11 08 23](https://cloud.githubusercontent.com/assets/13458260/17594505/6b62f1f0-5f9e-11e6-9c3b-f093fe6de4c5.jpg)

**Comment by ccrisan** [comment]
@RudyRipDraw have you configured the wpa_supplicant settings as indicated [here](https://github.com/ccrisan/motioneyeos/wiki/Troubleshooting-Raspberry-PI-Models-A-%28Plus%29-And-Zero)?

**Comment by RudyRipDraw** [comment]
Calin,

Thank you for the response.  I've moved the SD over to the Pi B and have connectivity to the Ethernet.

Sorry, but I just a little more help on the config of the wifi.

Specifically where should I put the wpa_supplicant.conf file with my ssid and password?

![screenhunter_2779 aug 11 11 13](https://cloud.githubusercontent.com/assets/13458260/17599599/cc2c61b8-5fb4-11e6-8539-8c6cb02f86f7.jpg)

![screenhunter_2781 aug 11 11 16](https://cloud.githubusercontent.com/assets/13458260/17599697/28d871ea-5fb5-11e6-8b50-f778b6c20afe.jpg)

**Comment by RudyRipDraw** [comment]
just need to config wifi... :-) 
everything else is working on the B


![screenhunter_2782 aug 11 11 24](https://cloud.githubusercontent.com/assets/13458260/17599952/52006d74-5fb6-11e6-9741-7e4eb4f11227.jpg)

**Comment by RudyRipDraw** [comment]
or I don't know how to correctly invoke the write.sh script

![screenhunter_2783 aug 11 11 37](https://cloud.githubusercontent.com/assets/13458260/17600395/2abdf46e-5fb8-11e6-8cea-a97891764489.jpg)

**Comment by ccrisan** [comment]
You need to choose *one* of those methods, not all of them :)

If you have managed to boot the image on a RPi model B, just enable Advanced Settings and, under the Network settings section, enable and configure your WiFi.

If you wanted to go by providing your own wpa_supplicant.conf, you should have placed it on the boot partition using your *Windows* machine (since you probably wouldn't have had access to a Linux machine).

**Comment by RudyRipDraw** [comment]
Calin,

Thank you for your help.  It is all working.  I made some rookie moves, so let me summary my steps so that perhaps the next person can leverage this thread instead of your time.

1.  The Pi Zero runs the same image as the Pi Model B, so if you have a Pi Model, start with that unit because it has Ethernet

2. Install the wifi dongle and wired Ethernet

3. Boot the Pi Model B and find out the ip address from the router

4.  Point browser to ip address of Pi Model B from another machine on the same lan

5.  Login as admin, which defaults to no password
![screenhunter_2784 aug 11 14 57](https://cloud.githubusercontent.com/assets/13458260/17606472/8cf89e38-5fd4-11e6-877f-e6544560f14f.jpg)

6. Change Advance Setting to ON otherwise you will not see the Network options
![screenhunter_2785 aug 11 14 57](https://cloud.githubusercontent.com/assets/13458260/17606491/a9fc2130-5fd4-11e6-928d-c5abdb056464.jpg)

7. Under Network, enter the Wireless Network Name and Wireless Network Key,  then click the Apply
![screenhunter_2786 aug 11 14 59](https://cloud.githubusercontent.com/assets/13458260/17606515/c5f07f12-5fd4-11e6-90be-1b556604ee68.jpg)

8. System will reboot.  But power off the Pi Model B and move the SD and wifi dongle to the Pi Zero 

This works for me!

thanks

**Comment by ccrisan** [comment]
Perfect! Thanks for sharing this.

**Comment by pjockey** [comment]
I just downloaded the 20160801 image and all I get is the square rainbow screen and nothing else. I've given it 5 minutes, but nothing. I'm running a RP 3 with a SainSmart Infrared Night Vision Surveillance Camera. I've played with some Python programing and the camera is recognize with the code. 

Not sure where to go from here. Any suggestions, please reply

Thanks

**Comment by ccrisan** [comment]
Which image variant have you downloaded? Have you extracted it before writing it to the card?

**Comment by pjockey** [comment]
I've figure this, was trying to put the RP 3 image into a 2. Fixed,my bad. I have the system booted up and connected to my network with wifi. It stops when it asked for the user ID. I entered admin with no password and I'm sitting at the CLI. Now what do I do?Scott                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone on the TELUS network.                                                                                                                                                                                                                From: Calin CrisanSent: Saturday, August 20, 2016 16:05To: ccrisan/motioneyeosReply To: ccrisan/motioneyeosCc: S Milliken; CommentSubject: Re: [ccrisan/motioneyeos] Raspberry PI Zero (#182)Which image variant have you downloaded? Have you extracted it before writing it to the card?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ccrisan/motioneyeos","title":"ccrisan/motioneyeos","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ccrisan/motioneyeos"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ccrisan in #182: Which image variant have you downloaded? Have you extracted it before writing it to the card?"}],"action":{"name":"View Issue","url":"https://github.com/ccrisan/motioneyeos/issues/182#issuecomment-241226650"}}}

**Comment by ccrisan** [comment]
@pjockey have your read [this faq entry](https://github.com/ccrisan/motioneyeos/wiki/FAQ#i-am-only-getting-white-on-black-text-on-my-monitor-where-is-my-ui)?

P.S. why have you chosen to comment on this particular issue? You problem is not even remotely related to Raspberry PI Zero, nor the WiFi.

**Comment by TheKitro** [comment]
Hi 
I cant geht my wifi config work :(

Situation:
Windows 10   #Workpc
Notepad++   #Editor
Raspi Zero 1.3 
Connected:
Night Vision Camera
HDMI
USB Hub  (Wifi Dongle,  Mouse - Keyboad Logitech Dongle)
SD Card 8 GB

What I done under Windows:
Download motioneyeos-raspberrypi-20160801.img.gz
Extract motioneyeos-raspberrypi-20160801.img
Format SD with SDFormater
Write Image to SD with Win32DiskImager
Create  wpa_supplicant.conf file on SD with Notepad++
Insert Text:
"update_config=1
ctrl_interface=/var/run/wpa_supplicant

network={
    scan_ssid=1
    ssid="your_network"
    psk="your_password"
}"
Replace your_network with my networkname  (e.g.  ssid="myprivateLAN")
Replace same way the psk
Change encoding of file in UTF8  and  UNIX Linebreak.
Save file
Plug SD in Raspi Zero
Boot
Get reboot circle. Error no wired network: no device  :(((

What do i wrong ?

Best Regards  
Cornflake
PS: Very nice tool I used it on good working in Raspi2 too.

**Comment by ccrisan** [comment]
Make sure to:

1. name your `wpa_supplicant.conf` file correctly.
2. place your `wpa_supplicant.conf` in the correct directory (the root of the boot partition, next to e.g. config.txt)
3. place your `wpa_supplicant.conf` on the boot partition *before* booting your OS from the SD card for the first time.

P.S. if there's no mention of WiFI or wpa_supplicant in your boot log, then the file is not taken into consideration and most likely you did not follow one of the above conditions.

**Comment by TheKitro** [comment]
It WORKS :)))
Ok my fault was to boot it first time without the wpa_supplicant.conf file. in the second boot this file wasn't included.

Additional Question:
I'd like to use this zero motioneye  on my friends home.  For this I have later to change the WLAN config. Is it possible to add 2 WLAN configs in the wpa_supplicant.conf file?  or change this file later over windows textfiles?

Big thx for your response and help
Cornflake

**Comment by ccrisan** [comment]
motionEyeOS does not support more than one WiFi connection. If you must use two WiFi connections, please try Raspbian + motionEye.

**Comment by calyerm** [comment]
Pi Zero:
Using 20160915 + usb network dongle ... this is working ... but
Limited menu options (Example no Motion control option ) ... 
Very low frame rate .. 2 fps ...  using  standard OS and other streaming methods , frame rates for 640x480 ..are good ..

**Comment by fideocam** [comment]
Has anybody tried the new Zero W with motioneyes? I guess you could configure wifi password into the img before burning and just check the IP from wifi AP.

**Comment by wdawson001** [comment]
@fideocam Follow the instructions here #804 (comment)

The official releases haven't been updated but I recompiled from the latest repo, so it works.

**Comment by kiridashi** [comment]
@fideocam

running this configuration since a week (zeroW+NoirCam+motioneyeos)

setup was easy, just created a "wpa_supplicant. conf" file an entered wifi- ssid and -key.
