### ISSUE TITLE
Hub / Correlator

### ISSUE THREAD

**Issue by miguelt678** [ccrisan/motioneyeos#1870]
Rather than writing my own, I’d like to use motioneye as a hub.  However, I would like each remote motioneye to write the files themselves.  Is that possible?
Otherwise, I would like the remote motioneye to write the file to a common location, and then call a web hook with the details.  Is that possible?

**Comment by ccrisan** [comment]
If you're referring to media files, that won't be possible without a major effort because media files are created directly by Motion, which runs on each individual device, assuming you're talking about a hub with multiple remote motionEye cameras.

If you want your media files to be created by one central server, use the central server + (fast) network cameras setup, instead of hub + remote motionEye cameras. Also please refer to https://github.com/ccrisan/motioneyeos/wiki/Usage-Scenarios.
