### ISSUE TITLE
Device not starting up after a reboot? Is there a way I can do it remotely?

### ISSUE THREAD

**Issue by sambunting** [ccrisan/motioneyeos#1916]
I'm running "motioneyeos-raspberrypi3-20181209" (I don't know the exact version I'm afraid). on a Raspberry Pi 3 B+ which has two cameras running, one a V4L2 camera, the other a USB webcam.

I noticed something strange with the UI and some of the fields getting mixed up and after refreshing the UI, both camera feeds were then showing the same camera feed. I decided to just reboot the server.

After a few minutes, nothing happened. The board hasn't rebooted.

The problem is, I don't have physical/direct access to the Raspberry Pi itself.

The Pi is powered by a power over ethernet connection. I've tried switching the injector off and back on again and nothing is happening. I've tried sending a Wake on LAN message but nothing has happened either. 

Is there any way I can remotely startup MotionEyeOS? I'd normally just pull out the power cable and plug it back in, but as I said earlier I don't have access to the device.

Any help would be really appreciated as I have no idea what is going on right now.

**Comment by ccrisan** [comment]
Rebooting the board can only be done by reconnecting the power, if you don't have access to it anymore.

If you have upgraded to a newer version, I'm afraid there's not much you can do about your setup other than reflashing from scratch. As per [these instructions](https://github.com/ccrisan/motioneyeos/wiki/Upgrading-From-Versions-Prior-To-20190119), the automatic upgrade procedure is broken between before and after 20190119 so you should have followed the instructions rather than updating from UI.
