### ISSUE TITLE
What happens if storage becomes unavailable??

### ISSUE THREAD

**Issue by flasher4401** [ccrisan/motioneyeos#201]
If i am using an external hard drive for instance, will there be a message/warning as soon as it becomes unavailable? (Write failed for reasons like: full, faulty, not connected)

If its full, is there a tool to handle it? (remove oldest files?)
Otherwise i think it is needed to let the users know that recording is not working

**Comment by Gordon-1** [comment]
That is a great question and is a reasonable experiment for anyone to try and then report any problems in the issues section of Github.

Test hardware:  RaspPi3 with RasPi camerea, MotionEyeOS pre-release version 20160306. The following was my experience, YMMV.

Using a flash USB drive for storage (which becomes /dev/sda) then pulling the USB drive out while the system is running (not recommended), the system continues to run however when motion is detected, system tries to save the files but fails.  Error are reported in the log files but the user is not otherwise notified.

Reinserting the flash drive in the same USB port ( and hoping your system does not crash because of the power surge and the flash drive does not become corrupted), the flash drive is assigned /dev/sd**b** however MotionEyeOS is still trying to save to sd**a **so the saves fail.

So it's not good if you lose your USB connection to storage but if you also have file uploading on (to dropbox and/or google drive) then I assume that would still work.

This is from dmesg after the flash drive was removed:
[Wed Dec 31 19:01:10 1969] FAT-fs (sda1): FAT read failed (blocknr 3071)
[Wed Dec 31 19:01:10 1969] FAT-fs (sda1): FAT read failed (blocknr 3071)
[Wed Dec 31 19:01:11 1969] bcm2835-v4l2: error 0 waiting for frame completion

And when the flash drive was put back in the same USB port:

[Wed Dec 31 19:01:31 1969] usb 1-1.4: new high-speed USB device number 5 using dwc_otg
[Wed Dec 31 19:01:31 1969] usb 1-1.4: New USB device found, idVendor=0930, idProduct=6545
[Wed Dec 31 19:01:31 1969] usb 1-1.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[Wed Dec 31 19:01:31 1969] usb 1-1.4: Product: DataTraveler SE9
[Wed Dec 31 19:01:31 1969] usb 1-1.4: Manufacturer: Kingston
[Wed Dec 31 19:01:31 1969] usb 1-1.4: SerialNumber: 00187D1174F5EC70700084EA
[Wed Dec 31 19:01:31 1969] usb-storage 1-1.4:1.0: USB Mass Storage device detected
[Wed Dec 31 19:01:31 1969] scsi host1: usb-storage 1-1.4:1.0
[Wed Dec 31 19:01:31 1969] fat__get_entry: 22 callbacks suppressed
[Wed Dec 31 19:01:31 1969] FAT-fs (sda1): Directory bread(block 32768) failed
[Wed Dec 31 19:01:31 1969] FAT-fs (sda1): Directory bread(block 32769) failed
[Wed Dec 31 19:01:31 1969] FAT-fs (sda1): Directory bread(block 32770) failed
[Wed Dec 31 19:01:31 1969] FAT-fs (sda1): Directory bread(block 32771) failed
