### ISSUE TITLE
clean video output from motioneyeos 2020 on RPI3

### ISSUE THREAD

**Issue by jojo2203** [ccrisan/motioneyeos#2705]
Hello,

i would like to have a clean video, i.e. without border, control characters, header for further processing in obs studio. At the same time, however, I would like to have the action control buttons displayed on the mobile phone or a second computer in order to be able to control the pan tilt. How could I implement this? 

Thanks. jojo

**Comment by starbasessd** [comment]
Turn off text overlay, and feed from port 8081, however you lose the text overlay. If its a network cam, you can load the camera as camera 1 and camera 2 and feed from port 8081, and  run from camera 2

On March 21, 2021, at 4:04 PM, jojo2203 ***@***.***> wrote:

Hello,

i would like to have a clean video, i.e. without border, control characters, header for further processing in obs studio. At the same time, however, I would like to have the action control buttons displayed on the mobile phone or a second computer in order to be able to control the pan tilt. How could I implement this?

Thanks. jojo

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { ***@***.***": "<a href="http://schema.org">http://schema.org</a>", ***@***.***": "EmailMessage", "potentialAction": { ***@***.***": "ViewAction", "target": "<a href="https://github.com/ccrisan/motioneyeos/issues/2705">https://github.com/ccrisan/motioneyeos/issues/2705</a>", "url": "<a href="https://github.com/ccrisan/motioneyeos/issues/2705">https://github.com/ccrisan/motioneyeos/issues/2705</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { ***@***.***": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by starbasessd** [comment]
BTW, it would be helpful to know the info requested in the issue template to help more fully.

**Comment by jojo2203** [comment]
Thanks for the fast help. The additional specification of the port number 8081 in OBS Studio was the crucial point. Now I have a clean image even without the header.

Thanks. jojo
