### ISSUE TITLE
Network with no internet using evertz Master clock

### ISSUE THREAD

**Issue by BrandonHortman** [ccrisan/motioneyeos#2761]
Preliminary Docs

I confirm that I have read the CONTRIBUTING guide before opening this issue.
I confirm that I have read the FAQ before opening this issue.

motionEyeOS Version

motionEyeOS 20200606

Board Model

Raspberry Pi Zero W

Camera
My camera model is: Pi v2

Network Connection

My motionEyeOS unit is connected to the network via: WiFi

I manage a network at an Olympic stadium. The network doesn't have internet connectivity,  but the server gets NTP from an evertz master clock in our production studio. 

After working with it for a week and reading the log files,  I believe I'm not getting time from the server,  since it's not 1970 of course lol

After connecting to the wifi, getting an ip, it tries to initialize the eth0 (not connected)  then panics.

Is there a workaround for this?

**Comment by starbasessd** [comment]
Since you can't access Settings, Expert Settings, you can create a file: /boot/date.conf (similar to the /boot/wpa_supplicant.conf file with your pre-boot wifi settings)
You would include the lines:
-----
DATE_TIMEOUT="10"  << in seconds, extend if needed
DATE_METHOD="ntp"   << see bellow
DATE_NTP_SERVER="www.xxx.yyy.zzz:pppp"   << ip address and port of ntp source
-----
I do not know if you are using internal DNS resolution so I suggest the ip address. If you are using DNS, you could replace the IP addresses with the name, like time.stadium.local (or whatever)
Full description here:
https://github.com/ccrisan/thingos/wiki/date.conf

**Comment by BrandonHortman** [comment]
Thank you for your reply. 

Maybe I am wrong about my diagnosis, because it still seems to panic. 

 Looking in my message log I see this: 

user.notice network: no default route, calling panic action

![VirtualBox_Ubuntu_23_06_2021_08_07_59_LI](https://user-images.githubusercontent.com/76578289/123094209-a21c9900-d3fa-11eb-8ebf-d27f475cbd16.jpg)


Boot log: 

![VirtualBox_Ubuntu_23_06_2021_08_13_57](https://user-images.githubusercontent.com/76578289/123094704-35ee6500-d3fb-11eb-829d-af108c345759.png)

**Comment by starbasessd** [comment]
It would appear that your DHCP server is not giving a default gateway, or, if you are setting a static, you did not set the default gateway.

**Comment by starbasessd** [comment]
For diagnostics, you also might change the watch status: 
create a file:
/boot/watch.conf
put the following lines in it:
-----
LINK_WATCH="false"
IP_WATCH="false"
-----
This should have the effect of stopping the panics, but at the cost of not knowing if networking is failing. If you have console access (monitor & keyboard) this would at least bring the system up to check other things.

**Comment by starbasessd** [comment]
What is your status?

**Comment by BrandonHortman** [comment]
My apologies. I just had a baby! 😃
You were also dead on, I did not have a gateway. Everything works fine. 

Thank you

**Comment by starbasessd** [comment]
Good deal, congratulations, and the next 18 years will be very interesting...  :)
