### ISSUE TITLE
The Schedules is not working

### ISSUE THREAD

**Issue by peterd550** [ccrisan/motioneyeos#2837]
I have set the schedule so motion eye to record from 7 am 10 pm but it has still recorded video

![image](https://user-images.githubusercontent.com/15135115/140828047-0f036e9a-5e8a-4706-b91f-49a0b3fc088d.png)

**Comment by starbasessd** [comment]
Is the Time Zone set correctly and the time & name overlays correct?

**Comment by peterd550** [comment]
Yes that's the first thing I thought of.
All correct and set to Melbourne and is overlays are showing correct time

I am using this as my sntp server  1.au.pool.ntp.org

**Comment by peterd550** [comment]
I have SSH into the Pi and it is correct

**Comment by starbasessd** [comment]
I'm sorry... Which OS? 20200606 or dev20201026?

**Comment by peterd550** [comment]
I am using dev20201026

**Comment by starbasessd** [comment]
I'll check and let you know, I'm on another Bullseye issue...

**Comment by peterd550** [comment]
Any chance you had a look into this issue?

**Comment by starbasessd** [comment]
Not yet, I was working on a Bullseye issue. It's number 1 on my hit list for today after a nap...

**Comment by peterd550** [comment]
Ok thanks 
I'm AEST so bedtime tomorrow

**Comment by peterd550** [comment]
![image](https://user-images.githubusercontent.com/15135115/140905963-2bb62777-2bd0-4c12-8459-4c993e07ae87.png)

**Comment by peterd550** [comment]
Here is a resent screenshot

**Comment by starbasessd** [comment]
OK, dug a little deeper. My  mistake, I never noticed that Working Hours only applies to Motion Detection, not to all recordings. Thinking about another 'work around' for your circumstance/use case. Let me test a bit...

**Comment by starbasessd** [comment]
Looking for a more elegant process than the 2 copies of the config file and switching them at morning and evening as posted before. It definitely could be an 'enhancement', since if you are not using motion detection, there is no way to use working times...

**Comment by starbasessd** [comment]
Using crontab to simply start and stop recording using motion web controls does not work well due to too many checks needed to handle booting up / rebooting / power off / on cycles. Deep in thought. Even a 'simple' script is now over 30 lines... Depressing... I am still looking at it, though.

**Comment by starbasessd** [comment]
Unfortunately, my skills are lacking. Bullseye is becoming like some M$ upgrades. Making changes, leaving stuff out, etc, just because they can. My brain is mush. 
I wrote a nice set of instructions at: https://github.com/ccrisan/motioneyeos/issues/2779#issuecomment-882773284 to resolve an issue where someone wanted to change a particular camera setting for overnight.
For you, the easiest would be to have your overnight settings be no Movie, and daytime enable Movie with Continuous Recording on. Unfortunately, Working Hours is only available (currently) with Motion Detection. I cannot figure out how to make it all work for your scenario / use case. 
I will leave this open as a Feature Request / Enhancement, to see if anyone else wants to take a stab at it, and maybe a Dev can come up with a better idea...

**Comment by peterd550** [comment]
Used out of these hours and works well
