### ISSUE TITLE
Willing to Maintain HAOS Addon?

### ISSUE THREAD

**Issue by Ryu945** [ccrisan/motioneyeos#2976]
I heard this project was taken over by a new maintainer.   Would it be possible for you to update the addon for HAOS and continue maintaining it since the old project is abandoned?  It is so out of date that sftp doesn't even work on it anymore.

**Comment by starbasessd** [comment]
Are you asking for someone to do the HA plugin, to do the motionEye update or what? They are 2 different projects (3 if you include motionEyeOS).
The HA plugin was never really well supported, always blaming issues on motionEye, but if motionEye or motionEyeOS was installed as a separate entity, it didn't exhibit the issues claimed. 
MotionEyeOS is stand-alone and not used/usable in HA.
The new motionEye Devs are working on getting it switched off of Python2.7 to Python3.x and are not actively working on bringing up motionEyeOS until they complete the conversion.

**Comment by Ryu945** [comment]
Thankyou for the information.   After the migration, could you update the HA addon?  Yes I am basically asking if the addon HA could be maintained.  It is by far the most convient way to use Motion Eye.

**Comment by coder0107git** [comment]
@Ryu945 I think there has been a misunderstanding. Both the `motionEye` and `motionEyeOS` projects are housed and maintained by the [`motioneye-project` github organization](https://github.com/motioneye-project). The HA addon isn't advocated for (officially), supported, or maintained by the `motionEye` devs. Since the HA addon is maintained by a different organization they will have to update it when `motionEye 0.43` is released.

**Comment by Ryu945** [comment]
Thankyou for the information.
