### ISSUE TITLE
Timelapse stuck at 0%?

### ISSUE THREAD

**Issue by micky2171** [ccrisan/motioneyeos#387]
![image](https://cloud.githubusercontent.com/assets/7550213/16710099/7fbfc2b4-461b-11e6-81c2-462bdf404487.png)

Is there any way that I can view and cancel other timelapses too?

**Comment by ccrisan** [comment]
Unfortunately not.

**Comment by micky2171** [comment]
Now it says 'Failed to create Timelapse' after a reboot?

**Comment by ccrisan** [comment]
Without starting the timelapse process? Just out of nowhere?

**Comment by micky2171** [comment]
I restarted the Pi and clicked Timelapse, 30 seconds, 30FPS, OK
It now gets to 1% and then errors. The same thing happens when trying to create a ZIP of every image

**Comment by ccrisan** [comment]
Most likely you have too many pictures to be processed and both the zip and the timelapse procedure fails for two possible reasons: (1) the process takes too much time or (2) the free memory is not available. You could attach your motioneye.log here so that we clear this up. However the solution in your case is to work with less pictures or to choose a more powerful hardware.
