### ISSUE TITLE
Banana PI camera

### ISSUE THREAD

**Issue by simbiotica-it** [ccrisan/motioneyeos#389]
hi, thanks for the great job.
I bought a bananaPi but is not recognized , is supported ?
[http://www.tme.eu/it/Document/187887186b98a8f78b47da2774a34f4c/BPI-CAMERA.pdf](url)
ciao!

**Comment by ccrisan** [comment]
No idea. Can you log in through SSH and see if you have the `/dev/video0` device file present?

**Comment by simbiotica-it** [comment]
the device /dev/video0 isn't present

**Comment by simbiotica-it** [comment]
[http://wiki.lemaker.org/BananaPro/Pi:Camera_Module](url)
I tried to load the modules on this page but the system responds : not found in modules.dep

**Comment by ccrisan** [comment]
Does it work with any of the official operating systems?

**Comment by simbiotica-it** [comment]
Tested with Lubuntu distribution, the WebCam works fine.
installed with:
sudo modprobe ov5640
sudo modprobe sun4i_csi0
tested with GUVCview

**Comment by ccrisan** [comment]
Unfortunately it seems that mainline integration of the BPi CSI camera is still a work in progress: http://linux-sunxi.org/Mainlining_Effort#Major_drivers.

**Comment by ektus** [comment]
I've got a Banana Pi and CSI camera as of this weekend, and ran into the same problem. The motioneyeos image (version 20160705) lacks the ov5640 and sund4i_sci0 driver modules. With Bananian as OS (latest version, Jessie-based), the camera works (sort of), and motion produces images when started stand-alone without further configuration, but MotionEye doesn't find the internal camera due to errors. I'll report them over on the MotionEye tracker.
Would it be worthwhile copying over the two modules from the Bananian install? If so, how?

**Comment by bortek** [comment]
Closing his issue due to inactivity. If stil interested please post your question in the forum page.
