### ISSUE TITLE
PPP

### ISSUE THREAD

**Issue by anupsm28** [ccrisan/motioneyeos#403]
I am trying to interface Sim 908 with raspberry pi 3 having motioneyeOS. I have added pppd through Buildroot. But pon is not working.  apn    auth   extra  modem   pin, folders are created at the path /data/etc/ppp ..

**Comment by ccrisan** [comment]
1. There is no "official" support for for mobile network modems in motionEyeOS, due to how crappy most of the existing USB modems are and due to the fact that the unit will most likely be inaccessible from the internet.

2. pppd is already present in the OS image and some kind of untested support exists for this type of connection.

3. There is no `pon`. The modem connection is handled automatically by other scripts.

4. Your best bet is to use the `writeimage.sh` to preconfigure your 3G connection (using the `-m` option).
