### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by perardf** [ccrisan/motioneyeos#45]
Will it be possible to have an offline mode in order to detect motion even in place without internet access ? I would like to get that in order to install it on construction site.

thanks in advance for your help

**Comment by ccrisan** [comment]
motionEyeOS is not designed to be ran without internet connection. You can try it if you want but you will definitely won't have the correct system time.

**Comment by ektus** [comment]
Without correct system time, it won't record any images.With link watchdog active, the system will reboot upon losing the link, thus will also reset the time to 1970 and cease operation. Not a good behaviour for a security device, IMHO.

Regards
Ektus.

**Comment by ccrisan** [comment]
I don't see the connection between the *link* and the system time, but I agree that the general behaviour when dealing with current date/time can and should be improved.

**Comment by ektus** [comment]
By default, the link watchdog is active. For my first tests, I installed the system and let it running, sitting on the window sill. Then went off to work, switching off the router and all other equipment except the RPi. Result: Reboot of the RPi by the watchdog, failure to get time and date and IP-address due to unavailability of the connection, and no recording whatsoever, even with date 1970. Disabling the watchdog the next day did allow the RPi to stay up and running albeit the router being off again. So the offline condition doesn't necessarily stop the motioneyeos system, but it won't recover from any reboot during that time (power outage, whatever). I haven't been investigating the exact cause, though.
