### ISSUE TITLE
Snapshot doesn't work after about 15 seconds

### ISSUE THREAD

**Issue by ComputerSmiths** [ccrisan/motioneyeos#48]
Raspberry Pi2 running the latest release: 20151103

If I get a snapshot from http://m200pi/picture/1/current/ every 10 seconds it works fine, but if I wait 15 seconds, I get a zero size file returned.

Does the same thing in my Perl code and Safari browser.

**Comment by ccrisan** [comment]
It's the expected behaviour. After 10 seconds of no picture requests (a configurable timeout), the internal MJPG client will disconnect to save resources. The next time a picture request arrives, a new MJPG client is created; but due to the asynchronous nature of the motionEye server, a frame is not immediately available to be served, and therefore an empty response is sent.
