### ISSUE TITLE
PIR Sensors ModMyPi Box

### ISSUE THREAD

**Issue by nextgen1979** [ccrisan/motioneyeos#605]
Hello, 

I possible to use the modmypi box with the PIR Sensors included with motioneye os ? 

Thanks in advance 

Nicolas

**Comment by db414813** [comment]
This is a cool feature and I believe it's planned. Sooner or later.

**Comment by ril3y** [comment]
@ccrisan I would be willing to implement this but I am not really sure where to start.  Can you give me a suggestion on where you would start poking around if you were going to do this?  Turns out these PIR modules just output a HIGH ttl level for 2 seconds then go a back down to low.  

Pretty simple.  It might be a good enough of an option to put "take picture on motion" or "run this script" when this GPIO goes high.  Thoughts?

Willing to help just not familiar enough with the project.

**Comment by fti7** [comment]
Is there any command we could execute to trigger MotionEyeOSs internal "Motion Detection" Mechanism (Recording Pictures/Videos/whatever configured)?

An Daemon which polls an GPIO Pin + Executes this Command would be very easy

**Comment by ccrisan** [comment]
Not yet.

**Comment by cephasiii** [comment]
i am interested in this feature as well. looking forward to seeing it implemented.

**Comment by hellyberry** [comment]
This will be very usful with a generic interface to use other sensors also.

**Comment by jasaw** [comment]
See issue #842 .

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
