### ISSUE TITLE
Flag or Interrupt to RP3 with Jessie

### ISSUE THREAD

**Issue by o3aaron** [ccrisan/motioneyeos#699]
Quick Question.  I got this working perfectly on an RP Zero.  I saw in previous issue discussion MQTT is not yet supported.  Is there another quick way to send a flag/interrupt to another RP3?  It doesnt need to be complex but I just want my RP3 with Jessie to be able to react when motion is detected from my RP zero with motioneye.

**Comment by sylvaindc** [comment]
You should be able to run a scipt on motion detection. Which should allow
you to do everything including sending an MQTT message if you have a
suitable client. Alternatively, you could do a simple wget
http://YourPI3/WhateverCall or do something with SSH.

**Comment by o3aaron** [comment]
OK that would be perfect.  I thought I saw some there in this forum that mqtt was not supported yet but I will give it a try.  SSH would also work well.  Thank u

**Comment by sylvaindc** [comment]
To be honest, i had to google mqtt. If there is some client that you can
interface with from the a script than it should work without integration

On Sun, 15 Jan 2017 at 17:30, o3aaron <notifications@github.com> wrote:

OK that would be perfect. I thought I saw some there in this forum that
mqtt was not supported yet but I will give it a try. SSH would also work
well. Thank u




—
You are receiving this because you commented.


Reply to this email directly, view it on GitHub
<https://github.com/ccrisan/motioneyeos/issues/699#issuecomment-272706068>,
or mute the thread

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
