### ISSUE TITLE
Time update

### ISSUE THREAD

**Issue by martymoose** [ccrisan/motioneyeos#71]
My time newer seems to update
always 1970
rpi2  latest version wifi
any ideas  what log i can check
is there a way to delay start until have network time
cheers  great os

**Comment by ccrisan** [comment]
Do you have a direct (i.e. no proxy), working internet connection on your PI? Is your DNS properly configured? Please send me your `boot.log`, `dmesg.log` and `messages.log` files.

No there's no way to delay the startup process until time is available, simply because there are users that don't care about the current time.

**Comment by martymoose** [comment]
hi thanks here you go
just needed the time to embed in video

**Comment by ccrisan** [comment]
I'm sorry what video? Could you please send me the log files at ccrisan at gmail dot com?

**Comment by MarekITPro** [comment]
My 3 pence: If Date Method is set to NTP it works fine and picks up the time, when set to HTTP it does not.

**Comment by martymoose** [comment]
Hi mate just got home
i updated my 3 rpi to the new version
and they all work fine date from start works and embeded in stream fine saves in data folder as wel

thanks again
