### ISSUE TITLE
Wifi dongle not recognized (RT2800usb issue)

### ISSUE THREAD

**Issue by haragog** [ccrisan/motioneyeos#753]
I've bought the pi hut wifi dongle specific for the raspberry pi (listed as a RALINK RT5370 chipset), which works fine in raspbian. In motioneyeos (raspberry pi zero) it gives an rt2800usb driver issue leading to a reboot loop. With a RPI3 (with Ethernet), when activating it under networking setting, it displays a red ! symbol, In the dmesg.log I find this:

[Thu Jan  1 00:00:06 1970] usb 1-1.5: reset high-speed USB device number 4 using dwc_otg
[Thu Jan  1 00:00:06 1970] ieee80211 phy1: rt2x00_set_rt: Info - RT chipset 5390, rev 0502 detected
[Thu Jan  1 00:00:06 1970] ieee80211 phy1: rt2x00_set_rf: Info - RF chipset 5370 detected
[Thu Jan  1 00:00:06 1970] ieee80211 phy1: Selected rate control algorithm 'minstrel_ht'
[Thu Jan  1 00:00:06 1970] usbcore: registered new interface driver rt2800usb
I'm stumped... ;/

**Comment by jschun** [comment]
My experience is that MotionEyeOS first needs a wired network address. With that address you can logon to the WebGUI and via Advanced settings you can configure your wireless network SSID and Password. After that you can shutdown the Pi zero, plug in your Pi Hut Wifi dongle and bootup. The wifi dongle will work I use the same one. MotionEyeOS version for the raspberrypi1 with date 20170212.

I also bought this in order to give my Pi zero a wired connection while I still have keyboard and mouse ability (later you can also plug in your wifi dongle and have both Wired and wireless!).

https://nl.aliexpress.com/item/Adroit-Brand-New-Micro-USB-to-Network-LAN-Ethernet-RJ45-Adapter-with-3-Port-USB-2/32610315110.html?spm=2114.13010608.0.0.zfe3RF

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
