### ISSUE TITLE
video device fps changes video streaming fps

### ISSUE THREAD

**Issue by shinji2009** [ccrisan/motioneyeos#793]
hi. 
video device fps changes video streaming fps fo no reason. for example if streaming fps is 5 and i change video device fps to 10, streaming become 10 too.
thank you.

**Comment by ccrisan** [comment]
It's not for no reason. It's because most users increase their video device framerate and expect an increased framerate in their UI. Or this is only possible if the streaming framerate is also increased.

If you must have a higher device (capture) framerate while keeping a smaller streaming framerate, you can decrease the later afterwards.
