### ISSUE TITLE
Rpi 3 Bitrate/ Large filesize

### ISSUE THREAD

**Issue by lbrdv** [ccrisan/motioneyeos#847]
Heey guys,

I'm not very experienced in MotionEye. I just installed it on my RaspberryPi 3. It is a great program! I like it.

I have a question. I am (motion) recording at this moment with 1280x720. The Quality is 75% and the output to a SMB server is .MP4 .H264. FPS = 15

The video's are quite laggy. And what I see that the bitrate is quite high: 15461kbps (for example). A 30 second movie is already 50MB.

Anyone suggestions how I can lower the file size without losing to much quality.

Thanks for your help already! :)

Regards,

Lester

**Comment by leinad13** [comment]
I have a similar setup with rpi3 and motioneyeos, just started using it recently. You're right, this is a great piece of software. I was having issues at 20FPS 720p with my Logitech USB C930e cam. So I've switched to 15FPS, 800x600 and am still having a few issues. 

Some of the videos are absolutely perfect, others when played back in recent VLC (on multiple machines) capture the first 10 - 20 seconds of video, then the encoding seems to be corrupt. The picture and time hang for a while then springs back to life. 

The reason i think the encoding is corrupt, is because if you move the slider to a point where the picture looks frozen - it sometimes plays a bit of video. 

I was using a 0.7A PSU for the pi, so i switched it to a 2A PSU and am still having issues. Next thing, i'm going to try is a different SD card....

**Comment by bortek** [comment]
Closing this issue due to interest. If still interested please post your question in the forum page.
