### ISSUE TITLE
Feature Request: How's about running midori in kiosk mode

### ISSUE THREAD

**Issue by bdheeman** [ccrisan/motioneyeos#849]
How's about, installing wayland/weston and just run midori or something like that in kiosk mode so that we can view/watch everything by just hooking an HDMI monitor, keyboard and mouse to the RPi itself?

**Comment by ccrisan** [comment]
This is not going to happen to motionEyeOS because:

 * all the graphical packages would significantly increase the image size and we want to keep this as lightweight as possible
 * the browser running motionEye UI would eat up a lot of resources and the overall performance would be unacceptable
 * motionEyeOS is supposed to behave like a firmware for a RPi (or similar) netcam; having a monitor showing the actual stream attached to the netcam board itself defeats the purpose
