### ISSUE TITLE
Timelapse camera's, not getting the maximum resolution.

### ISSUE THREAD

**Issue by sderoos** [ccrisan/motioneyeos#874]
Hello! 

First of all I want to say thank you for all the effort put in this project, it's awesome! 

We are using this OS on three Pi's that are creating a timelapse on a shipyard where a new ship is being build. Before I found this project we used some scripts that created images and uploads them to a webserver. Those scripts created images that had the max resolution (2592×1944). 

In Motioneye I can set this resolution, the images are 2592×1944, but it looks like the image is just enlarged. We have a much smaller view now with Motioneye.

 Example from same point of view with old timelapse scripts (sorry, I don't have original images, but you will get it):
https://image.ibb.co/ghcwfa/9b8da807_f0a8_4d43_9705_7b17787e4e78.jpg

Motioneye when using normal resolution (1920x1080):
https://image.ibb.co/f8ftRF/11_24_30.jpg

Motioneye when resolution is set to 2592x1944:
https://image.ibb.co/igDrDv/11_25_03.jpg

This is a small timelapse I made with MotionEyeOS with the outside camera:) :
https://vimeo.com/211845633

**Comment by ccrisan** [comment]
Well the two resolutions don't have the same aspect ratio (1.77 vs 1.33). Instead of distorting the image, the camera firmware apparently prefers cutting it. It may also have to deal with video mode vs. stills mode which could be controlled via bcm2835-v4l2 module parameters. It needs some experimentation though. I recommend that you seek help on RPi-specific forums and get back with a solution, as I don't have one for you :)

**Comment by sderoos** [comment]
Ok, thank you!
