### ISSUE TITLE
Communication / IPv6 Problem?

### ISSUE THREAD

**Issue by SKAente** [ccrisan/motioneyeos#924]
Hi,
first of all: Thank you very much, Ccrisan, for this easy and excellent OS. 
I have set up the OS on a RPi 3 and a RPi Zero W. Both installations work basically well.
I'm currently dealing with the following issues:
- The RPi Zero seems to be not powerful enough to record 30fps at a resolution of 1600x1200. Is there an optimum resolution/frame-ratio for the RPi Zero? I will record videos/pics with a distance of approx. 10 m.
- I tried to setup Pushover notifications and an upload to my dropbox. Both didn't work. I suspect it is an IPv6 issue, so I cannot contact this external services (because my provider uses IPv6.) Is there any way to setup push notifications and dropbox upload? (maybe another pi as an IPv4 "distributor"?!)
- The system is not able to get the current time/date. Could this be an IPv6-issue, too?
Thank you in advance, I would really appreciate if you have answers to my questions and issues and kind regards from Germany.

**Comment by ccrisan** [comment]
> - The RPi Zero seems to be not powerful enough to record 30fps at a resolution of 1600x1200. Is there an optimum resolution/frame-ratio for the RPi Zero? I will record videos/pics with a distance of approx. 10 m.

Not really. You'll have to experiment a bit before deciding what's best for you.

> - I tried to setup Pushover notifications and an upload to my dropbox. Both didn't work. I suspect it is an IPv6 issue, so I cannot contact this external services (because my provider uses IPv6.) Is there any way to setup push notifications and dropbox upload? (maybe another pi as an IPv4 "distributor"?!)

motionEyeOS does not support IPv6. Unless you can obtain IPv4 connectivity from your provider, you'll have to find a way to encapsulate it. I can't help you with that, due to lack of experience.

> - The system is not able to get the current time/date. Could this be an IPv6-issue, too?
Thank you in advance, I would really appreciate if you have answers to my questions and issues and kind regards from Germany.

In order to fetch the current date/time, motionEyeOS requires an internet connection. So yes, given the IPv6 problem, that is probably the issue here as well.
