### ISSUE TITLE
RPI zero - Fast Network Camera - Best Settings

### ISSUE THREAD

**Issue by Gman1988** [ccrisan/motioneyeos#973]
Hi, does anyone knew what is the optimal settings to get optimal performance in FNC mode?

I already have 256 ram for GPU and overclocked using settings PI ZERO.

Any other improvements?
More ram for GPU will change anything?

**Comment by ccrisan** [comment]
Reduce the image quality to something between 10 and 20 and I think you'll be pleased with the outcome.

**Comment by Gman1988** [comment]
Wow, thanks for quick answer, but i need to ask stupid question ;]

What is the difference between resolution and image quality ? I mean the impact on the image i can see ?

The amount of the RAM for GPU have also impact ?

And does in the FNC mode "monitoring system" settings working ? because i dont see any effect on the image.

**Comment by ccrisan** [comment]
Your questions are not stupid. Resolution refers to the number of pixels that the image is composed of (its actual dimensions), while the quality refers to the overall JPEG quality. Here's an image I found googling that should somehow exemplify this quality: http://help.adobe.com/en_US/fireworks/cs/using/images/oe_jpg_loss.png. From my experience with FNC mode, a quality of 10 to 20 is still acceptable.

The amount of GPU memory (and the GPU itself) doesn't have any impact on the performance so don't bother tweaking it.

Many features, including the monitoring info, are not available in FNC mode, in order to improve the performance.
