### ISSUE TITLE
Timestamp

### ISSUE THREAD

**Issue by dabi236** [ccrisan/motioneyeos#98]
I have motioneyeos successfully running on two Raspberry Pi 2's.  This first RPi board controls two cameras (RPi camera and a USB Logitech). The second RPi controls a waveshare night vision camera.  The system is a standalone and is not hooked to the internet.  When the RPi's boot up they are not able to get current date using http:.   Is there any way of setting the current date and time when not hooked to the internet?  I have attached a screen shot from the camera showing timestamp.

![screen shot 2016-01-02 at 6 04 19 pm](https://cloud.githubusercontent.com/assets/16521070/12076513/8977802e-b17b-11e5-95ca-a5adf254c1a7.png)

**Comment by MarekITPro** [comment]
This is tracked on #71 
I get the same problem, it only works if you set it to use NTP instead of HTTP.

**Comment by dabi236** [comment]
Thanks for the response.  I'm not sure where to change it to NTP.

**Comment by dabi236** [comment]
Sorry found it

**Comment by MarekITPro** [comment]
You can change it under Expert Settings/Date Method.
What version of motioneyeos are you running ?

**Comment by dabi236** [comment]
I'm running version 20151206.  When I change it to NTP and apply the new setting the date is still 1969-12-31 and the time is also not correct.

**Comment by MarekITPro** [comment]
Ehm, can you backup your config and update to 20151230 - my Raspi2 is running this latest build and with HTTP selected it updates the date about 10 minutes after booting up. 
For NTP setup I am assuming you get response when: "ping 0.pool.ntp.org".
Attach your messages.log and boot.log files - will take a look.

**Comment by dabi236** [comment]
Upgraded to 20151230.  
With date method set to HTTP, I ran the camera for 15 minutes and there was no date/time correction. It shows 1970-01-01, 00:15:30.  When I set the date method to NTP I get the same results.  With the date method set to NTP I also typed in "ping 0.pool.ntp.org". I get the following response "bad address '0.pool.ntp.org"

[boot.docx](https://github.com/ccrisan/motioneyeos/files/76465/boot.docx)
[Motion.docx](https://github.com/ccrisan/motioneyeos/files/76466/Motion.docx)

**Comment by ektus** [comment]
Without Internet, neither HTTP nor NTP have a chance to work as both need a connection. In this case, you would need a hardware clock with battery buffer and get the time from that one. The necessary command has been included in recent builds, but I don't know if it's been activated in the startup scripts yet as I've since switched to Raspbian Wheezy to try and use Pikrellcam in parallel.
https://github.com/ccrisan/motioneyeos/issues/61
https://github.com/ccrisan/motioneyeos/issues/45

**Comment by Mikiya83** [comment]
Or you can use another computer in your private network as NTP server and usr it in your Pi, but it's a bit tricky.

**Comment by Chiny91** [comment]
A bit tricky agreed but satisfying to implement it on another Raspberry Pi.
http://www.satsignal.eu/ntp/Raspberry-Pi-NTP.html

This setup turns out to be very reliable and quite capable of servicing a network of perhaps a dozen phones, tablets, TVs, gadgets, motionEyeOS... and a couple of external friends.

**Comment by bortek** [comment]
Looks like this is no longer an issue. Please reopen otherwise.

**Comment by beankylla** [comment]
so i think the same underlying issue still applies: I want to setup a cron with a curl command to update a dydns entry, but the command does not work and i get a "bad address" message.
Trying to ping google.com or any web adress gives me a similar response.
pinging 8.8.8.8 works beautifully.
is anything preventind DNS resolve here?

**Comment by Mistahbass** [comment]
I used NTP and this server :
ntpdate ntp.ubuntu.com

Works like a charm

Cheers, Brock
