### ISSUE TITLE
How secure and patched is the HTTP engine against hacking?

### ISSUE THREAD

**Issue by RichardRadford** [ccrisan/motioneyeos#990]
If I want to open the web engine to the internet how up to date / secure is it?

Recently found a couple of cheap web cameras had been comprised due to various HTTP exploits.

Thanks

**Comment by bortek** [comment]
What you can d is to exract the information about the components and their versions using SSH connection and see how up to date their are. If you consider it being outdated I would suggest using a proxy server with authentication to get to the MotioneyeOS host. That way you will minimize the security impact. Also if you open it up onthe internet try to setup some high ports instead of HTTP/80.
